### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by marcvs** [clibs/list#23]
We're using this code and want to package our software (deb + rpm).

I'm not sure if we can (should) simply copy your code into our (MIT-Licensed) repo and be done with it, or if we have to get this code here packaged as a deb and rpm, too.

The latter is probably cleaner, but I'm not sure, if there are plans to build packages from the maintainer of list.

Any ideas?

**Comment by stephenmathieson** [comment]
Hello! No, there are no plans of maintaining a deb or rpm here. Instead we suggest using clib to manage small dependencies like this.
