### ISSUE TITLE
shared library

### ISSUE THREAD

**Issue by marcvs** [clibs/list#32]
Hi There,

a debian package that I maintain depends on on list.

Is there a good reason that you don't compile into a shared library, but just into a static one?

**Comment by marcvs** [comment]
Ping

**Comment by Isty001** [comment]
I guess there is no reason why we shouldn't also compile a shared lib. If you can, please open a PR to extend the Makefile, or I'll take a look at it when I have some time.

**Comment by marcvs** [comment]
Ok; PR Submitted

**Comment by marcvs** [comment]
Another note: I'm depending on this code in a debian package, hence I need to add your copyright.
I understand this code is MIT licensed, still I need a Copyright holder name.
Do you have one for me?

**Comment by marcvs** [comment]
My bad; Found what I needed in the license file
