### ISSUE TITLE
Install with less generic names?

### ISSUE THREAD

**Issue by musicinmybrain** [clibs/list#38]
I’m looking at packaging this library in Fedora Linux. I see that some work has already been done to make it suitable for Debian.

Since the name of the library (`list`) is extremely generic, would you consider any of the following adjustments to the `Makefile`?

- Install the header as `$(PREFIX)/include/clibs/list.h` instead of `$(PREFIX)/include/list.h`. Dependent packages could either `#include <clibs/list.h>`, or compile with `-I/usr/include/clibs`.
- Rename `liblist.so` to something like `libclibs_list.so`.
- Rename `liblist.a` to something like `libclibs_list.a`.

If so, I’m happy to provide the necessary PR.

**Comment by musicinmybrain** [comment]
Do you have any thoughts on this? I can work with whatever decision you make, but it would be nice to know before I submit the package for review. Thanks!

**Comment by stephenmathieson** [comment]
I'm fine with this, as long as clib users can still `clib install list` and `include "deps/list/list.h"`.

/cc @jwerle any thoughts?

**Comment by jwerle** [comment]
yep I echo @stephenmathieson so long as we preserve backwards compat and expectations

**Comment by musicinmybrain** [comment]
Completed with https://github.com/clibs/list/releases/tag/0.3.0
