### ISSUE TITLE
New release for 0.4.0

### ISSUE THREAD

**Issue by marcvs** [clibs/list#44]
Hi There,

could you release the 0.4.0 (or 0.4.1 with PR #43  included) on github? 
The packaging scripts for Debian and RPM  like to make use of these
releases to access the sources.

Best,
Marcus.

**Comment by stephenmathieson** [comment]
Yes, I will do this today 👍

**Comment by marcvs** [comment]
Hi There,

I noticed that the tag 0.4.0 contains a Makefile that defines versions 0.2.0  Which causes my builds to fail :)

**Comment by stephenmathieson** [comment]
Please use 0.4.1 (just released).

**Comment by marcvs** [comment]
Thanks; Done.
